baseurl: "http://jonaswouters.be/"
languageCode: "en-us"
title: "Jonas Wouters"
MetaDataFormat: "yaml"
layoutdir: "theme"
permalinks:
  post: /:year/:month/:title/
params:
  name: "Jonas Wouters"
  avatar: "http://www.gravatar.com/avatar/030f01a17257e1b5ecde30246c681d99.jpg?s=512"
  bio: "Freelance developer @ [Just Works](http://justworks.be). Father, geek, gamer. [@jonaswouters](http://twitter.com/jonaswouters). "
  twitter: "jonaswouters"
  copyright: "2015 Jonas Wouters"
  license: "Test"
